pre-commit:
  parallel: true
  jobs:
    - name: lint go
      run: golangci-lint run --fix --timeout 2m
      glob: "*.go"
      stage_fixed: true
commit-msg:
  commands:
    commitlint:
      run: pnpx commitlint --edit {1}
