// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveGroup = `-- name: ArchiveGroup :one
UPDATE groups SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at
`

// Soft-deletes a group by setting archived_at
func (q *Queries) ArchiveGroup(ctx context.Context, id int64) (*Group, error) {
	row := q.db.QueryRow(ctx, archiveGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const countGroupAdmins = `-- name: CountGroupAdmins :one
SELECT COUNT(*) AS admin_count FROM memberships
WHERE group_id = $1 AND role = 'admin' AND accepted_at IS NOT NULL
`

// Counts active admins in a group
func (q *Queries) CountGroupAdmins(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupAdmins, groupID)
	var admin_count int64
	err := row.Scan(&admin_count)
	return admin_count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) AS member_count FROM memberships
WHERE group_id = $1 AND accepted_at IS NOT NULL
`

// Counts active members in a group
func (q *Queries) CountGroupMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var member_count int64
	err := row.Scan(&member_count)
	return member_count, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (
    name, handle, description, parent_id, created_by_id,
    members_can_add_members, members_can_add_guests, members_can_start_discussions,
    members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments,
    members_can_delete_comments, members_can_announce, members_can_create_subgroups,
    admins_can_edit_user_content, parent_members_can_see_discussions
) VALUES (
    $1, $2, $3, $4, $5,
    COALESCE($6, TRUE), COALESCE($7, TRUE), COALESCE($8, TRUE),
    COALESCE($9, TRUE), COALESCE($10, FALSE), COALESCE($11, TRUE),
    COALESCE($12, TRUE), COALESCE($13, FALSE), COALESCE($14, FALSE),
    COALESCE($15, FALSE), COALESCE($16, FALSE)
)
RETURNING id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string      `json:"name"`
	Handle      string      `json:"handle"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.Int8 `json:"parent_id"`
	CreatedByID int64       `json:"created_by_id"`
	Column6     interface{} `json:"column_6"`
	Column7     interface{} `json:"column_7"`
	Column8     interface{} `json:"column_8"`
	Column9     interface{} `json:"column_9"`
	Column10    interface{} `json:"column_10"`
	Column11    interface{} `json:"column_11"`
	Column12    interface{} `json:"column_12"`
	Column13    interface{} `json:"column_13"`
	Column14    interface{} `json:"column_14"`
	Column15    interface{} `json:"column_15"`
	Column16    interface{} `json:"column_16"`
}

// sqlc queries for groups table
// See: data-model.md for entity definition
// Creates a new group with the given parameters
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (*Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Handle,
		arg.Description,
		arg.ParentID,
		arg.CreatedByID,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getGroupByHandle = `-- name: GetGroupByHandle :one
SELECT id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at FROM groups WHERE handle = $1
`

// Retrieves a group by its URL-safe handle (case-insensitive via CITEXT)
func (q *Queries) GetGroupByHandle(ctx context.Context, handle string) (*Group, error) {
	row := q.db.QueryRow(ctx, getGroupByHandle, handle)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at FROM groups WHERE id = $1
`

// Retrieves a group by its ID
func (q *Queries) GetGroupByID(ctx context.Context, id int64) (*Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const handleExists = `-- name: HandleExists :one
SELECT EXISTS(SELECT 1 FROM groups WHERE handle = $1) AS exists
`

// Checks if a handle is already taken
func (q *Queries) HandleExists(ctx context.Context, handle string) (bool, error) {
	row := q.db.QueryRow(ctx, handleExists, handle)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupsByUser = `-- name: ListGroupsByUser :many
SELECT g.id, g.name, g.handle, g.description, g.parent_id, g.created_by_id, g.archived_at, g.members_can_add_members, g.members_can_add_guests, g.members_can_start_discussions, g.members_can_raise_motions, g.members_can_edit_discussions, g.members_can_edit_comments, g.members_can_delete_comments, g.members_can_announce, g.members_can_create_subgroups, g.admins_can_edit_user_content, g.parent_members_can_see_discussions, g.created_at, g.updated_at FROM groups g
JOIN memberships m ON m.group_id = g.id
WHERE m.user_id = $1
  AND m.accepted_at IS NOT NULL
  AND ($2::boolean = TRUE OR g.archived_at IS NULL)
ORDER BY g.name
`

type ListGroupsByUserParams struct {
	UserID          int64 `json:"user_id"`
	IncludeArchived bool  `json:"include_archived"`
}

// Lists all groups a user is an active member of
// Excludes archived groups by default unless include_archived is true
func (q *Queries) ListGroupsByUser(ctx context.Context, arg ListGroupsByUserParams) ([]*Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUser, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.ParentID,
			&i.CreatedByID,
			&i.ArchivedAt,
			&i.MembersCanAddMembers,
			&i.MembersCanAddGuests,
			&i.MembersCanStartDiscussions,
			&i.MembersCanRaiseMotions,
			&i.MembersCanEditDiscussions,
			&i.MembersCanEditComments,
			&i.MembersCanDeleteComments,
			&i.MembersCanAnnounce,
			&i.MembersCanCreateSubgroups,
			&i.AdminsCanEditUserContent,
			&i.ParentMembersCanSeeDiscussions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubgroupsByParent = `-- name: ListSubgroupsByParent :many
SELECT id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at FROM groups
WHERE parent_id = $1
  AND ($2::boolean = TRUE OR archived_at IS NULL)
ORDER BY name
`

type ListSubgroupsByParentParams struct {
	ParentID        pgtype.Int8 `json:"parent_id"`
	IncludeArchived bool        `json:"include_archived"`
}

// Lists all subgroups under a parent group
func (q *Queries) ListSubgroupsByParent(ctx context.Context, arg ListSubgroupsByParentParams) ([]*Group, error) {
	rows, err := q.db.Query(ctx, listSubgroupsByParent, arg.ParentID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.ParentID,
			&i.CreatedByID,
			&i.ArchivedAt,
			&i.MembersCanAddMembers,
			&i.MembersCanAddGuests,
			&i.MembersCanStartDiscussions,
			&i.MembersCanRaiseMotions,
			&i.MembersCanEditDiscussions,
			&i.MembersCanEditComments,
			&i.MembersCanDeleteComments,
			&i.MembersCanAnnounce,
			&i.MembersCanCreateSubgroups,
			&i.AdminsCanEditUserContent,
			&i.ParentMembersCanSeeDiscussions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveGroup = `-- name: UnarchiveGroup :one
UPDATE groups SET archived_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at
`

// Restores an archived group
func (q *Queries) UnarchiveGroup(ctx context.Context, id int64) (*Group, error) {
	row := q.db.QueryRow(ctx, unarchiveGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    members_can_add_members = COALESCE($4, members_can_add_members),
    members_can_add_guests = COALESCE($5, members_can_add_guests),
    members_can_start_discussions = COALESCE($6, members_can_start_discussions),
    members_can_raise_motions = COALESCE($7, members_can_raise_motions),
    members_can_edit_discussions = COALESCE($8, members_can_edit_discussions),
    members_can_edit_comments = COALESCE($9, members_can_edit_comments),
    members_can_delete_comments = COALESCE($10, members_can_delete_comments),
    members_can_announce = COALESCE($11, members_can_announce),
    members_can_create_subgroups = COALESCE($12, members_can_create_subgroups),
    admins_can_edit_user_content = COALESCE($13, admins_can_edit_user_content),
    parent_members_can_see_discussions = COALESCE($14, parent_members_can_see_discussions),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, handle, description, parent_id, created_by_id, archived_at, members_can_add_members, members_can_add_guests, members_can_start_discussions, members_can_raise_motions, members_can_edit_discussions, members_can_edit_comments, members_can_delete_comments, members_can_announce, members_can_create_subgroups, admins_can_edit_user_content, parent_members_can_see_discussions, created_at, updated_at
`

type UpdateGroupParams struct {
	ID                             int64       `json:"id"`
	Name                           pgtype.Text `json:"name"`
	Description                    pgtype.Text `json:"description"`
	MembersCanAddMembers           pgtype.Bool `json:"members_can_add_members"`
	MembersCanAddGuests            pgtype.Bool `json:"members_can_add_guests"`
	MembersCanStartDiscussions     pgtype.Bool `json:"members_can_start_discussions"`
	MembersCanRaiseMotions         pgtype.Bool `json:"members_can_raise_motions"`
	MembersCanEditDiscussions      pgtype.Bool `json:"members_can_edit_discussions"`
	MembersCanEditComments         pgtype.Bool `json:"members_can_edit_comments"`
	MembersCanDeleteComments       pgtype.Bool `json:"members_can_delete_comments"`
	MembersCanAnnounce             pgtype.Bool `json:"members_can_announce"`
	MembersCanCreateSubgroups      pgtype.Bool `json:"members_can_create_subgroups"`
	AdminsCanEditUserContent       pgtype.Bool `json:"admins_can_edit_user_content"`
	ParentMembersCanSeeDiscussions pgtype.Bool `json:"parent_members_can_see_discussions"`
}

// Updates group fields (partial update pattern)
func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (*Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MembersCanAddMembers,
		arg.MembersCanAddGuests,
		arg.MembersCanStartDiscussions,
		arg.MembersCanRaiseMotions,
		arg.MembersCanEditDiscussions,
		arg.MembersCanEditComments,
		arg.MembersCanDeleteComments,
		arg.MembersCanAnnounce,
		arg.MembersCanCreateSubgroups,
		arg.AdminsCanEditUserContent,
		arg.ParentMembersCanSeeDiscussions,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.ParentID,
		&i.CreatedByID,
		&i.ArchivedAt,
		&i.MembersCanAddMembers,
		&i.MembersCanAddGuests,
		&i.MembersCanStartDiscussions,
		&i.MembersCanRaiseMotions,
		&i.MembersCanEditDiscussions,
		&i.MembersCanEditComments,
		&i.MembersCanDeleteComments,
		&i.MembersCanAnnounce,
		&i.MembersCanCreateSubgroups,
		&i.AdminsCanEditUserContent,
		&i.ParentMembersCanSeeDiscussions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
