// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int64              `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	Username      string             `json:"username"`
	PasswordHash  string             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	Key           string             `json:"key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
