// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, username, password_hash, key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, username, password_hash, email_verified, deactivated_at, key, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Key          string `json:"key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Key,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DeactivatedAt,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET deactivated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, username, password_hash, email_verified, deactivated_at, key, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DeactivatedAt,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, username, password_hash, email_verified, deactivated_at, key, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DeactivatedAt,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByKey = `-- name: GetUserByKey :one
SELECT id, email, name, username, password_hash, email_verified, deactivated_at, key, created_at, updated_at FROM users WHERE key = $1
`

func (q *Queries) GetUserByKey(ctx context.Context, key string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByKey, key)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DeactivatedAt,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, name, username, password_hash, email_verified, deactivated_at, key, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DeactivatedAt,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = $2 WHERE id = $1
`

type UpdateUserEmailVerifiedParams struct {
	ID            int64 `json:"id"`
	EmailVerified bool  `json:"email_verified"`
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
